#!/bin/bash
# Daily Tasks Scheduler - Cron Job
# Part of Silver Tier AI Employee
#
# Add to crontab:
# 0 9 * * * /path/to/schedulers/daily_tasks.sh

VAULT_PATH="E:/hackhaton0_personal_ai_employe/AI_Employee_Vault"
WATCHER_DIR="E:/hackhaton0_personal_ai_employe/watchers"
LOG_FILE="$VAULT_PATH/Logs/daily_schedule_$(date +%Y%m%d).log"

echo "============================================" >> "$LOG_FILE"
echo "Daily Tasks Started: $(date)" >> "$LOG_FILE"
echo "============================================" >> "$LOG_FILE"

# 1. Generate daily plan
echo "[1/4] Generating daily plan..." >> "$LOG_FILE"
python3 "$WATCHER_DIR/reasoning_loop.py" \
    --vault "$VAULT_PATH" \
    --action plan \
    --plan-name "Daily_$(date +%Y%m%d).md" >> "$LOG_FILE" 2>&1

# 2. Generate LinkedIn content calendar
echo "[2/4] Generating content calendar..." >> "$LOG_FILE"
python3 "$WATCHER_DIR/linkedin_poster.py" \
    --vault "$VAULT_PATH" \
    --action calendar >> "$LOG_FILE" 2>&1

# 3. Check for urgent items
echo "[3/4] Checking for urgent items..." >> "$LOG_FILE"
URGENT_COUNT=$(find "$VAULT_PATH/Needs_Action" -name "*.md" -exec grep -l "priority: high" {} \; | wc -l)
echo "Found $URGENT_COUNT urgent items" >> "$LOG_FILE"

# 4. Create daily summary
echo "[4/4] Creating daily summary..." >> "$LOG_FILE"
cat > "$VAULT_PATH/Dashboard_Daily_$(date +%Y%m%d).md" << EOF
# Daily Summary - $(date +%Y-%m-%d)

## Stats
- Urgent Items: $URGENT_COUNT
- Total Pending: $(find "$VAULT_PATH/Needs_Action" -name "*.md" | wc -l)
- Completed Today: $(find "$VAULT_PATH/Done" -name "*.md" -mtime -1 | wc -l)

## Activity
See detailed logs in: $LOG_FILE

## Plan
See daily plan: Plans/Daily_$(date +%Y%m%d).md

---
*Generated by daily scheduler*
EOF

echo "============================================" >> "$LOG_FILE"
echo "Daily Tasks Completed: $(date)" >> "$LOG_FILE"
echo "============================================" >> "$LOG_FILE"
