#!/bin/bash
# Weekly Tasks Scheduler - Cron Job
# Part of Silver Tier AI Employee
#
# Add to crontab (every Monday at 9am):
# 0 9 * * 1 /path/to/schedulers/weekly_tasks.sh

VAULT_PATH="E:/hackhaton0_personal_ai_employe/AI_Employee_Vault"
WATCHER_DIR="E:/hackhaton0_personal_ai_employe/watchers"

echo "============================================"
echo "Weekly Tasks Started: $(date)"
echo "============================================"

# 1. Generate comprehensive weekly plan
echo "[1/3] Generating weekly plan..."
python3 "$WATCHER_DIR/reasoning_loop.py" \
    --vault "$VAULT_PATH" \
    --action plan \
    --plan-name "Weekly_$(date +%Y%m%d).md"

# 2. Create CEO Briefing
echo "[2/3] Creating CEO Briefing..."
cat > "$VAULT_PATH/CEO_Briefing_$(date +%Y%m%d).md" << EOF
# CEO Briefing - Week of $(date +%Y-%m-%d)

## Executive Summary

### Key Metrics
- Pending Tasks: $(find "$VAULT_PATH/Needs_Action" -name "*.md" | wc -l)
- Completed This Week: $(find "$VAULT_PATH/Done" -name "*.md" -mtime -7 | wc -l)
- Approval Rate: $(calculate_approval_rate)

### Priority Items
$(list_high_priority_items)

### Watcher Status
- FileSystem: Active
- Approval: Active
- Gmail: $(check_gmail_status)

### Recommendations
1. Review urgent items in Needs_Action
2. Approve pending items in Drafts folder
3. Check weekly plan for detailed action items

## Detailed Reports
- Activity logs: $VAULT_PATH/Logs/
- Weekly plan: Plans/Weekly_$(date +%Y%m%d).md
- Content calendar: Plans/Content_*.md

---
*Generated by Weekly Scheduler*
*Silver Tier AI Employee*
EOF

# 3. Generate week's worth of LinkedIn content
echo "[3/3] Generating LinkedIn content..."
python3 "$WATCHER_DIR/linkedin_poster.py" \
    --vault "$VAULT_PATH" \
    --action calendar

echo "============================================"
echo "Weekly Tasks Completed: $(date)"
echo "============================================"
